# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
ADMIN_NAME: OMI Administrator
ADMIN_EMAIL: user@example.com
ADMIN_PASSWORD: changeme
ROLES: [admin, claims, outlet]
SMS_GATEWAY_SERVICE_ID: <<SERVICE_ID>>
SMS_GATEWAY_CHANNEL_ID: <<CHANNEL_ID>>
SMS_GATEWAY_PASSWORD: <<PASSWORD>>
SMS_GATEWAY_URL: https://dragon.brainstorm.co.uk:1089/Gateway/
DEVICE_ATLAS_LICENCE_KEY: <<KEY>>
BASE_URL: http://localhost:3000/
BITLY_USERNAME: <<username>>
BITLY_PASSWORD: <<password>>
MIN_CLAIM_DAYS: 21
MPESA: 513201
AIRTEL: JAMBOPAY
JP_BUSINESS: demo@webtribe.co.ke
JP_SHARED_KEY: 6127482F-35BC-42FF-A466-276C577E7DF3
GMAIL_USERNAME: <<username>>
GMAIL_PASSWORD: <<password>>
TZ: Africa/Nairobi
SHORT_CODE: 22808
SMS_MAX_SEGMENT_LENGTH: 160
SPLIT_SMS: true
CLAIM_DATE_VALIDATION: false
MANDRILL_APIKEY: <<MANDRILL_APIKEY>>
MANDRILL_USERNAME: <<MANDRILL_USERNAME>>
KEYWORD: "Mobile, mombile, mobi, phone"
OMB_URL: http://korient.co.ke/omb
SEED_POLICY_NO: 1
CATALOG_VERSION: 1
UPDATE_FILE: catalogue_october.csv
FONEXPRESS_EMAIL: scadmin@fonexpress.net
CLAIM_REGISTRATION_EMAILS: scadmin@fonexpress.net, ombclaims@korient.co.ke
ANALYTICS_ID: sdfsdf
SITE: korient.co.ke
FEEDBACK_FROM_EMAIL: feedback@korient.co.ke
FEEDBACK_TO_EMAIL: mobile@korient.co.ke
ANALTICS_USERNAME: <<username>>
ANALYTICS_PASSWORD: <<password>>
DEBUG_DEVICE_ATLAS: false
DEBUG_DEVICE_ATLAS_MODEL: Safari - OS X
DEBUG_DEVICE_ATLAS_VENDOR: Apple